#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm constant/polyMesh/boundary > /dev/null 2>&1
rm -rf 0 > /dev/null 2>&1
rm system/topoSetDict > /dev/null 2>&1
#cp 0/alpha.water.orig 0/alpha.water

#------------------------------------------------------------------------------
