#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`



#runApplication blockMesh
#./Allrun.refineMesh


#rm -rf 0
#cp -r 0.orig 0

#runApplication setFields

#runApplication decomposePar

#runParallel renumberMesh -overwrite

#runParallel $(getApplication)

#foamMonitor -l postProcessing/residuals/0/residuals.dat 

runApplication reconstructPar
#runApplication $application

cd forceCoeffs
cp -r ../postProcessing/forceCoeffs/0/forceCoeffs.dat forceCoeffVelocity$1
cd ..
./Allrun.plot $1
cd plots
mv ../*.pdf .
cd ..

cd postProcessingFolder
cp -r ../postProcessing postProcessingVelocity$1
cd ..

runApplication -s yPlus \
    twoLiquidMixingFoam  -postProcess -func yPlus
cd yPlusValues
cp -r ../postProcessing/yPlus/*/yPlus.dat yPlusVelocity$1
cd ..


#------------------------------------------------------------------------------
