import os
def writeNutfile(nut):
    outfileName = os.getcwd() + '/0.orig/nut'
    f = open(outfileName, 'w')
    f.write("/*--------------------------------*- C++ -*----------------------------------*\ \n")
    f.write("| =========                 |                                                 | \n")
    f.write("| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           | \n")
    f.write("|  \\    /   O peration     | Version:  5                                     | \n")
    f.write("|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |\n")
    f.write("|    \\/     M anipulation  |                                                 | \n")
    f.write("\*---------------------------------------------------------------------------*/ \n")
    f.write("FoamFile \n")
    f.write("{ \n")
    f.write("    version     2.0; \n")
    f.write("    format      ascii; \n")
    f.write("    class       volScalarField; \n")
    f.write("    location     \"0\"; \n")
    f.write("    object      nut; \n")
    f.write("} \n")
    f.write("// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * // \n")
    f.write(" \n")
    f.write(" \n")
    f.write("dimensions      [0 2 -1 0 0 0 0]; \n")
    f.write(" \n")
    f.write("internalField   uniform %f; \n" %nut)
    f.write(" \n")
    f.write("boundaryField \n")
    f.write("{ \n")
    f.write("    //- Set patchGroups for constraint patches \n")
    f.write("    #includeEtc \"caseDicts/setConstraintTypes\" \n")
    f.write("    inlet \n")
    f.write("    { \n")
    f.write("        type            fixedValue; \n")
    f.write("        value           $internalField;\n")
    f.write("    } \n")
    f.write("    outlet \n")
    f.write("    { \n")
    f.write("       type            zeroGradient; \n")
    f.write("    } \n")
    f.write("    atmosphere \n")
    f.write("	{ \n")
    f.write("		type			zeroGradient;\n")
    f.write("	} \n")
    f.write("    atmosphereFrontOfBarge \n")
    f.write("	{ \n")
    f.write("		type			zeroGradient;\n")
    f.write("	} \n")
    f.write("	barge \n")
    f.write("	{ \n")
    f.write("        type            nutUSpaldingWallFunction;\n")
    f.write("\n")
    f.write("\n")
    f.write("        value           $internalField;\n")
    f.write("   } \n")
    f.write("} \n")
    f.write(" \n")
    f.write("// ************************************************************************* // \n")
    f.close()
    return None

if __name__ == "__main__":
    writeNutfile(0.10)
