import os
def writeUfile(velocity):
    outfileName = os.getcwd() + '/0.orig/U'
    f = open(outfileName, 'w')
    f.write("/*--------------------------------*- C++ -*----------------------------------*\ \n")
    f.write("| =========                 |                                                 | \n")
    f.write("| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           | \n")
    f.write("|  \\    /   O peration     | Version:  5                                     | \n")
    f.write("|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |\n")
    f.write("|    \\/     M anipulation  |                                                 | \n")
    f.write("\*---------------------------------------------------------------------------*/ \n")
    f.write("FoamFile \n")
    f.write("{ \n")
    f.write("    version     2.0; \n")
    f.write("    format      ascii; \n")
    f.write("    class       volVectorField; \n")
    f.write("    location     \"0\"; \n")
    f.write("    object      U; \n")
    f.write("} \n")
    f.write("// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * // \n")
    f.write(" \n")
    f.write("Umean %f; \n" %velocity)
    f.write("mUmean -%f; \n" %velocity)
    f.write(" \n")
    f.write("dimensions      [0 1 -1 0 0 0 0]; \n")
    f.write(" \n")
    f.write("internalField   uniform ($mUmean  0 0); \n")
    f.write(" \n")
    f.write("boundaryField \n")
    f.write("{ \n")
    f.write("    //- Set patchGroups for constraint patches \n")
    f.write("    #includeEtc \"caseDicts/setConstraintTypes\" \n")
    f.write("    outlet \n")
    f.write("    { \n")
    f.write("        //type               zeroGradient; \n")
    f.write("\n")
    f.write("		type            outletPhaseMeanVelocity; \n")
    f.write("        alpha           alpha.water; \n")
    f.write("        Umean           $Umean; \n")
    f.write("        value           $internalField; \n")
    f.write(" \n")
    f.write("    } \n")
    f.write("    inlet \n")
    f.write("    { \n")
    f.write("        type                    fixedValue; \n")
    f.write("        value                   $internalField; \n")
    f.write("    } \n")
    f.write("	barge \n")
    f.write("	{ \n")
    f.write("        type            movingWallVelocity; \n")
    f.write("        value           uniform (0 0 0); \n")
    f.write("	} \n")
    f.write("	atmosphereFrontOfBarge \n")
    f.write("	{ \n")
    f.write("       type                inletOutlet;\n")
    f.write("		inletValue			$internalField; \n")
    f.write("		value				$internalField; \n")
    f.write("    } \n")
    f.write("	atmosphere \n")
    f.write(" 	{\n")
    f.write("         type                    slip; 	\n")
    f.write(" 	}\n")
    f.write("} \n")
    f.write(" \n")
    f.write("// ************************************************************************* // \n")
    f.close()
    return None

if __name__ == "__main__":
    writeUfile(0.10)
