import os
def writeControlDictFile(velocity):
    outfileName = os.getcwd() + '/system/controlDict'
    f = open(outfileName, 'w')
    f.write("/*--------------------------------*- C++ -*----------------------------------*\ \n")
    f.write("| =========                 |                                                 | \n")
    f.write("| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           | \n")
    f.write("|  \\    /   O peration     | Version:  5                                     | \n")
    f.write("|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |\n")
    f.write("|    \\/     M anipulation  |                                                 | \n")
    f.write("\*---------------------------------------------------------------------------*/ \n")
    f.write("FoamFile \n")
    f.write("{ \n")
    f.write("    version     2.0; \n")
    f.write("    format      ascii; \n")
    f.write("    class       dictionary; \n")
    f.write("    location    \"system\"; \n")
    f.write("    object      controlDict; \n")
    f.write("} \n")
    f.write("// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * // \n")
    f.write(" \n")
    f.write("application     twoLiquidMixingFoam;//interFoam; \n")
    f.write("\n" )
    f.write("startFrom       latestTime;//startTime; \n")
    f.write(" \n")
    f.write("startTime       0; \n")
    f.write("\n")
    f.write("stopAt          endTime; \n")
    f.write("\n")
    f.write("endTime         50; \n")
    f.write(" \n")
    f.write("deltaT          1;//0.5; \n")
    f.write("\n")
    f.write("writeControl    adjustableRunTime; \n")
    f.write(" \n")
    f.write("writeInterval   10.0; \n")
    f.write(" \n")
    f.write("purgeWrite      0; \n")
    f.write("\n")
    f.write("writeFormat     binary;\n")
    f.write(" \n")
    f.write("writePrecision  6;//12;\n")
    f.write("\n")
    f.write("writeCompression uncompressed;\n")
    f.write("\n")
    f.write("timeFormat      general; \n")
    f.write("\n")
    f.write("timePrecision   6; \n")
    f.write("\n")
    f.write("runTimeModifiable yes; \n")
    f.write("\n")
    f.write("adjustTimeStep  yes;//no; \n")
    f.write("maxCo           1.0;\n")
    f.write("maxAlphaCo      1.0; \n")
    f.write("rDeltaTSmoothingCoeff 0.05; \n")
    f.write("rDeltaTDampingCoeff 0.5; \n")
    f.write("nAlphaSpreadIter    0; \n")
    f.write("nAlphaSweepIter     0; \n")
    f.write("maxDeltaT       1; \n")
    f.write(" \n")
    f.write("functions\n")
    f.write("{\n")
    f.write("    //#include \"cuttingPlane\"\n")
    f.write("\n")
    f.write("    #includeFunc    residuals \n")
    f.write("\n")
    f.write("    forceCoeffs\n")
    f.write("    {\n")
    f.write("        type                forceCoeffs;\n")
    f.write("        functionObjectLibs  (\"libforces.so\");\n")
    f.write("        writeControl       timeStep;\n")
    f.write("        writeInterval      1;\n")
    f.write("\n")
    f.write("        patches             (barge);\n")
    f.write("        p                   p;\n")
    f.write("        U                   U;\n")
    f.write("        rho                 rhoInf;\n")
    f.write("        log                 true;\n")
    f.write("\n")
    f.write("        liftDir             (0 0 1);\n")
    f.write("        dragDir             (-1 0 0);\n")
    f.write("        CofR                (0.3 0 0.075); // Rotation center\n")
    f.write("        pitchAxis           (0 1 0);\n")
    f.write("\n")
    f.write("        magUInf             %f;\n" %velocity) 
    f.write("        rhoInf              997; // Denisity fluid\n")
    f.write("        lRef                0.6; // Chord \n")
    f.write("        Aref                0.24;//0.345;//0.24;// Wetted surface ares, \n")
    f.write("    }\n")
    f.write("    forces\n")
    f.write("    {\n")
    f.write("        type            forces;\n")
    f.write("        libs            (\"libforces.so\");\n")
    f.write("        patches         (barge);\n")
    f.write("        rhoInf          997;\n")
    f.write("        log             on;\n")
    f.write("        writeControl    timeStep;\n")
    f.write("        writeInterval   1;\n")
    f.write("        CofR            (0.3 0 0.075); // Rotation center\n")
    f.write("    }\n")
    f.write("}\n")
    f.write("\n")
    f.write("// ************************************************************************* // \n")
    f.close()
    return None

if __name__ == "__main__":
    writeControlDictFile(0.10)
